title: "M. Mohsin Riaz"
author: "M. Mohsin Riaz"
description: "My personal blog — thoughts, experiences & journey"
permalink: /:title/
lang: "en"
future: true
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
show_excerpts: true
show_frame: false
show_sidebar: false
show_minimal: false
url: "https://m-mohsin-riaz.github.io"
baseurl: ""

navigation:
  - {file: "myjourney.md", title: "My Journey", icon: "book-open"}
  - {file: "about.md",     title: "About Me",    icon: "user"}
  - {file: "contact.md",   title: "Contact Me",  icon: "envelope"}
plugins:
  - jekyll-feed
  - jekyll-seo-tag
